# Generated by Django 3.2.5 on 2021-07-19 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyers', '0002_client'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
    ]
