# Generated by Django 3.2.5 on 2021-07-23 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_remove_car_buyer'),
        ('buyers', '0003_delete_client'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Buyer',
        ),
    ]
