# Generated by Django 3.2.5 on 2021-07-23 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyers', '0005_buyer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='from_singnal',
            field=models.BooleanField(default=True),
        ),
    ]
