# Generated by Django 3.2.5 on 2021-07-23 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_car_buyer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='buyer',
        ),
    ]
