# Generated by Django 3.2.5 on 2021-07-23 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_remove_car_buyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='test',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
