# Generated by Django 3.2.5 on 2021-07-23 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buyers', '0006_alter_buyer_from_singnal'),
        ('cars', '0005_car_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='buyer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='buyers.buyer'),
            preserve_default=False,
        ),
    ]
