# Generated by Django 3.2.5 on 2021-07-24 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buyers', '0007_test'),
        ('cars', '0007_remove_car_buyer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car_test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buyers.test')),
            ],
        ),
    ]
