# Generated by Django 3.2.5 on 2021-07-24 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_sales'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sales',
        ),
    ]
